### ISSUE TITLE
Создать функцию инициализатор

### ISSUE THREAD

**Issue by ilmpc** [geekycats-school/tglib#5]
- [x] Регистрирование доступных команд (/new_task) (можно сделать кнопкой)

- [x]  Загрузка сохраненного в #4 файла с отправленными задачами

**Comment by ghost** [comment]
Json object
json library python
with clause

**Comment by ilmpc** [comment]
Деплой не удался.
```
2020-11-06T23:31:37.466216+00:00 app[web.1]: Traceback (most recent call last):
2020-11-06T23:31:37.466243+00:00 app[web.1]:   File "./src/app.py", line 63, in <module>
2020-11-06T23:31:37.466605+00:00 app[web.1]:     main()
2020-11-06T23:31:37.466606+00:00 app[web.1]:   File "./src/app.py", line 46, in main
2020-11-06T23:31:37.466753+00:00 app[web.1]:     init()
2020-11-06T23:31:37.466754+00:00 app[web.1]:   File "./src/app.py", line 21, in init
2020-11-06T23:31:37.466891+00:00 app[web.1]:     with open(config.DATA_FILE, "r") as savefile:
2020-11-06T23:31:37.466896+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'stored_chats.json'
2020-11-06T23:31:37.538347+00:00 heroku[web.1]: Process exited with status 1
2020-11-06T23:31:37.589311+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by ghost** [comment]
> Деплой не удался.
> 
> ```
> 2020-11-06T23:31:37.466216+00:00 app[web.1]: Traceback (most recent call last):
> 2020-11-06T23:31:37.466243+00:00 app[web.1]:   File "./src/app.py", line 63, in <module>
> 2020-11-06T23:31:37.466605+00:00 app[web.1]:     main()
> 2020-11-06T23:31:37.466606+00:00 app[web.1]:   File "./src/app.py", line 46, in main
> 2020-11-06T23:31:37.466753+00:00 app[web.1]:     init()
> 2020-11-06T23:31:37.466754+00:00 app[web.1]:   File "./src/app.py", line 21, in init
> 2020-11-06T23:31:37.466891+00:00 app[web.1]:     with open(config.DATA_FILE, "r") as savefile:
> 2020-11-06T23:31:37.466896+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'stored_chats.json'
> 2020-11-06T23:31:37.538347+00:00 heroku[web.1]: Process exited with status 1
> 2020-11-06T23:31:37.589311+00:00 heroku[web.1]: State changed from starting to crashed
> ```

Извините, пожалуйста, мне недостаточно информации, чтобы понять, как чинить. Я не знаю, что такое heroku и как там этот тест проходил, где находился сам json и был ли он вообще.
